/**
 * GENERATED from docs/product/04-contracts/AUTHORIZATION_MATRIX.md — do not edit by hand.
 *
 * Regenerate: python3 tools/gen_authz_matrix_ts.py
 *
 * THIS IS PRESENTATION DATA. IT IS NOT AN AUTHORIZATION CONTROL.
 *   The server decides (apps/api/src/authz/policy.py, STEP-002.03). This copy
 *   exists so the interface can avoid offering an action that would be refused —
 *   a courtesy, not a gate. Anyone can edit the bundle that contains it.
 *
 * It is generated from the SAME markdown as the Python matrix (ADR-012), so the
 * two cannot drift apart. A drift test fails if they do.
 */

export const OPERATIONS = [
  'create_trip',
  'read_trip',
  'replace_brief',
  'build_evidence_pack',
  'generate_scenarios',
  'list_read_scenarios',
  'select_canonical_scenario',
  'create_what_if_edit',
  'modify_protected_item',
  'invite_collaborator',
  'booking_handoff',
  'activate_live_trip',
  'generate_repairs',
  'accept_repair',
  'submit_feedback',
  'export_delete_own_data',
  'override_destination_fact',
  'approve_high_impact_override',
  'read_coverage',
  'disable_provider_roll_back_model',
  'read_support_diagnostic_bundle',
  'query_knowledge_graph',
] as const;

export const ROLES = [
  'guest',
  'trip_owner',
  'trip_editor',
  'trip_viewer',
  'advisor',
  'curator',
  'ops_admin',
  'privacy_operator',
] as const;

export type Operation = (typeof OPERATIONS)[number];
export type Role = (typeof ROLES)[number];

export interface Rule {
  readonly allow: boolean;
  readonly audit: boolean;
  readonly condition: string | null;
}

export const MATRIX: Readonly<Record<string, Rule>> = {
  'create_trip:guest': { allow: true, audit: false, condition: 'own_resource' },
  'create_trip:trip_owner': { allow: true, audit: false, condition: null },
  'create_trip:trip_editor': { allow: false, audit: false, condition: null },
  'create_trip:trip_viewer': { allow: false, audit: false, condition: null },
  'create_trip:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'create_trip:curator': { allow: false, audit: false, condition: null },
  'create_trip:ops_admin': { allow: false, audit: false, condition: null },
  'create_trip:privacy_operator': { allow: false, audit: false, condition: null },
  'read_trip:guest': { allow: true, audit: false, condition: 'own_resource' },
  'read_trip:trip_owner': { allow: true, audit: false, condition: null },
  'read_trip:trip_editor': { allow: true, audit: false, condition: null },
  'read_trip:trip_viewer': { allow: true, audit: false, condition: null },
  'read_trip:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'read_trip:curator': { allow: false, audit: false, condition: null },
  'read_trip:ops_admin': { allow: false, audit: false, condition: null },
  'read_trip:privacy_operator': { allow: true, audit: true, condition: 'dsr_request' },
  'replace_brief:guest': { allow: true, audit: false, condition: 'own_resource' },
  'replace_brief:trip_owner': { allow: true, audit: false, condition: null },
  'replace_brief:trip_editor': { allow: true, audit: false, condition: null },
  'replace_brief:trip_viewer': { allow: false, audit: false, condition: null },
  'replace_brief:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'replace_brief:curator': { allow: false, audit: false, condition: null },
  'replace_brief:ops_admin': { allow: false, audit: false, condition: null },
  'replace_brief:privacy_operator': { allow: false, audit: false, condition: null },
  'build_evidence_pack:guest': { allow: true, audit: false, condition: 'own_resource' },
  'build_evidence_pack:trip_owner': { allow: true, audit: false, condition: null },
  'build_evidence_pack:trip_editor': { allow: true, audit: false, condition: null },
  'build_evidence_pack:trip_viewer': { allow: false, audit: false, condition: null },
  'build_evidence_pack:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'build_evidence_pack:curator': { allow: false, audit: false, condition: null },
  'build_evidence_pack:ops_admin': { allow: false, audit: false, condition: null },
  'build_evidence_pack:privacy_operator': { allow: false, audit: false, condition: null },
  'generate_scenarios:guest': { allow: true, audit: false, condition: 'own_resource' },
  'generate_scenarios:trip_owner': { allow: true, audit: false, condition: null },
  'generate_scenarios:trip_editor': { allow: true, audit: false, condition: null },
  'generate_scenarios:trip_viewer': { allow: false, audit: false, condition: null },
  'generate_scenarios:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'generate_scenarios:curator': { allow: false, audit: false, condition: null },
  'generate_scenarios:ops_admin': { allow: false, audit: false, condition: null },
  'generate_scenarios:privacy_operator': { allow: false, audit: false, condition: null },
  'list_read_scenarios:guest': { allow: true, audit: false, condition: 'own_resource' },
  'list_read_scenarios:trip_owner': { allow: true, audit: false, condition: null },
  'list_read_scenarios:trip_editor': { allow: true, audit: false, condition: null },
  'list_read_scenarios:trip_viewer': { allow: true, audit: false, condition: null },
  'list_read_scenarios:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'list_read_scenarios:curator': { allow: false, audit: false, condition: null },
  'list_read_scenarios:ops_admin': { allow: false, audit: false, condition: null },
  'list_read_scenarios:privacy_operator': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:guest': { allow: true, audit: false, condition: 'own_resource' },
  'select_canonical_scenario:trip_owner': { allow: true, audit: false, condition: null },
  'select_canonical_scenario:trip_editor': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:trip_viewer': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:advisor': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:curator': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:ops_admin': { allow: false, audit: false, condition: null },
  'select_canonical_scenario:privacy_operator': { allow: false, audit: false, condition: null },
  'create_what_if_edit:guest': { allow: true, audit: false, condition: 'own_resource' },
  'create_what_if_edit:trip_owner': { allow: true, audit: false, condition: null },
  'create_what_if_edit:trip_editor': { allow: true, audit: false, condition: null },
  'create_what_if_edit:trip_viewer': { allow: false, audit: false, condition: null },
  'create_what_if_edit:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'create_what_if_edit:curator': { allow: false, audit: false, condition: null },
  'create_what_if_edit:ops_admin': { allow: false, audit: false, condition: null },
  'create_what_if_edit:privacy_operator': { allow: false, audit: false, condition: null },
  'modify_protected_item:guest': { allow: true, audit: false, condition: 'explicit_unlock' },
  'modify_protected_item:trip_owner': { allow: true, audit: false, condition: 'explicit_unlock' },
  'modify_protected_item:trip_editor': { allow: false, audit: false, condition: null },
  'modify_protected_item:trip_viewer': { allow: false, audit: false, condition: null },
  'modify_protected_item:advisor': { allow: false, audit: false, condition: null },
  'modify_protected_item:curator': { allow: false, audit: false, condition: null },
  'modify_protected_item:ops_admin': { allow: false, audit: false, condition: null },
  'modify_protected_item:privacy_operator': { allow: false, audit: false, condition: null },
  'invite_collaborator:guest': { allow: false, audit: false, condition: null },
  'invite_collaborator:trip_owner': { allow: true, audit: false, condition: null },
  'invite_collaborator:trip_editor': { allow: false, audit: false, condition: null },
  'invite_collaborator:trip_viewer': { allow: false, audit: false, condition: null },
  'invite_collaborator:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'invite_collaborator:curator': { allow: false, audit: false, condition: null },
  'invite_collaborator:ops_admin': { allow: false, audit: false, condition: null },
  'invite_collaborator:privacy_operator': { allow: false, audit: false, condition: null },
  'booking_handoff:guest': { allow: true, audit: false, condition: 'own_resource' },
  'booking_handoff:trip_owner': { allow: true, audit: false, condition: null },
  'booking_handoff:trip_editor': { allow: true, audit: false, condition: null },
  'booking_handoff:trip_viewer': { allow: false, audit: false, condition: null },
  'booking_handoff:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'booking_handoff:curator': { allow: false, audit: false, condition: null },
  'booking_handoff:ops_admin': { allow: false, audit: false, condition: null },
  'booking_handoff:privacy_operator': { allow: false, audit: false, condition: null },
  'activate_live_trip:guest': { allow: false, audit: false, condition: null },
  'activate_live_trip:trip_owner': { allow: true, audit: false, condition: null },
  'activate_live_trip:trip_editor': { allow: false, audit: false, condition: null },
  'activate_live_trip:trip_viewer': { allow: false, audit: false, condition: null },
  'activate_live_trip:advisor': { allow: false, audit: false, condition: null },
  'activate_live_trip:curator': { allow: false, audit: false, condition: null },
  'activate_live_trip:ops_admin': { allow: false, audit: false, condition: null },
  'activate_live_trip:privacy_operator': { allow: false, audit: false, condition: null },
  'generate_repairs:guest': { allow: false, audit: false, condition: null },
  'generate_repairs:trip_owner': { allow: true, audit: false, condition: null },
  'generate_repairs:trip_editor': { allow: true, audit: false, condition: null },
  'generate_repairs:trip_viewer': { allow: false, audit: false, condition: null },
  'generate_repairs:advisor': { allow: true, audit: true, condition: 'delegation_record' },
  'generate_repairs:curator': { allow: false, audit: false, condition: null },
  'generate_repairs:ops_admin': { allow: false, audit: false, condition: null },
  'generate_repairs:privacy_operator': { allow: false, audit: false, condition: null },
  'accept_repair:guest': { allow: false, audit: false, condition: null },
  'accept_repair:trip_owner': { allow: true, audit: false, condition: null },
  'accept_repair:trip_editor': { allow: false, audit: false, condition: null },
  'accept_repair:trip_viewer': { allow: false, audit: false, condition: null },
  'accept_repair:advisor': { allow: false, audit: false, condition: null },
  'accept_repair:curator': { allow: false, audit: false, condition: null },
  'accept_repair:ops_admin': { allow: false, audit: false, condition: null },
  'accept_repair:privacy_operator': { allow: false, audit: false, condition: null },
  'submit_feedback:guest': { allow: true, audit: false, condition: 'own_resource' },
  'submit_feedback:trip_owner': { allow: true, audit: false, condition: null },
  'submit_feedback:trip_editor': { allow: true, audit: false, condition: null },
  'submit_feedback:trip_viewer': { allow: true, audit: false, condition: null },
  'submit_feedback:advisor': { allow: false, audit: false, condition: null },
  'submit_feedback:curator': { allow: false, audit: false, condition: null },
  'submit_feedback:ops_admin': { allow: false, audit: false, condition: null },
  'submit_feedback:privacy_operator': { allow: false, audit: false, condition: null },
  'export_delete_own_data:guest': { allow: true, audit: false, condition: 'own_resource' },
  'export_delete_own_data:trip_owner': { allow: true, audit: false, condition: null },
  'export_delete_own_data:trip_editor': { allow: true, audit: false, condition: 'own_resource' },
  'export_delete_own_data:trip_viewer': { allow: true, audit: false, condition: 'own_resource' },
  'export_delete_own_data:advisor': { allow: true, audit: false, condition: 'own_resource' },
  'export_delete_own_data:curator': { allow: false, audit: false, condition: null },
  'export_delete_own_data:ops_admin': { allow: false, audit: false, condition: null },
  'export_delete_own_data:privacy_operator': { allow: true, audit: true, condition: null },
  'override_destination_fact:guest': { allow: false, audit: false, condition: null },
  'override_destination_fact:trip_owner': { allow: false, audit: false, condition: null },
  'override_destination_fact:trip_editor': { allow: false, audit: false, condition: null },
  'override_destination_fact:trip_viewer': { allow: false, audit: false, condition: null },
  'override_destination_fact:advisor': { allow: false, audit: false, condition: null },
  'override_destination_fact:curator': { allow: true, audit: true, condition: null },
  'override_destination_fact:ops_admin': { allow: false, audit: false, condition: null },
  'override_destination_fact:privacy_operator': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:guest': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:trip_owner': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:trip_editor': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:trip_viewer': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:advisor': { allow: false, audit: false, condition: null },
  'approve_high_impact_override:curator': {
    allow: true,
    audit: false,
    condition: 'second_curator',
  },
  'approve_high_impact_override:ops_admin': {
    allow: true,
    audit: true,
    condition: 'UNSPECIFIED_see_DEC_010',
  },
  'approve_high_impact_override:privacy_operator': { allow: false, audit: false, condition: null },
  'read_coverage:guest': { allow: true, audit: false, condition: 'public_resource' },
  'read_coverage:trip_owner': { allow: true, audit: false, condition: null },
  'read_coverage:trip_editor': { allow: true, audit: false, condition: null },
  'read_coverage:trip_viewer': { allow: true, audit: false, condition: null },
  'read_coverage:advisor': { allow: true, audit: false, condition: null },
  'read_coverage:curator': { allow: true, audit: false, condition: null },
  'read_coverage:ops_admin': { allow: true, audit: false, condition: null },
  'read_coverage:privacy_operator': { allow: true, audit: false, condition: null },
  'disable_provider_roll_back_model:guest': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:trip_owner': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:trip_editor': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:trip_viewer': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:advisor': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:curator': { allow: false, audit: false, condition: null },
  'disable_provider_roll_back_model:ops_admin': { allow: true, audit: true, condition: null },
  'disable_provider_roll_back_model:privacy_operator': {
    allow: false,
    audit: false,
    condition: null,
  },
  'read_support_diagnostic_bundle:guest': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:trip_owner': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:trip_editor': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:trip_viewer': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:advisor': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:curator': { allow: false, audit: false, condition: null },
  'read_support_diagnostic_bundle:ops_admin': {
    allow: true,
    audit: true,
    condition: 'single_trip_scope',
  },
  'read_support_diagnostic_bundle:privacy_operator': {
    allow: true,
    audit: true,
    condition: 'single_trip_scope',
  },
  'query_knowledge_graph:guest': { allow: false, audit: false, condition: null },
  'query_knowledge_graph:trip_owner': { allow: false, audit: false, condition: null },
  'query_knowledge_graph:trip_editor': { allow: false, audit: false, condition: null },
  'query_knowledge_graph:trip_viewer': { allow: false, audit: false, condition: null },
  'query_knowledge_graph:advisor': { allow: false, audit: false, condition: null },
  'query_knowledge_graph:curator': { allow: true, audit: false, condition: 'facts_subgraph' },
  'query_knowledge_graph:ops_admin': {
    allow: true,
    audit: true,
    condition: 'code_graph_permission',
  },
  'query_knowledge_graph:privacy_operator': { allow: false, audit: false, condition: null },
};

/** Presentation-only check. The server is the control. */
export function mayAttempt(operation: Operation, role: Role): boolean {
  const rule = MATRIX[`${operation}:${role}`];
  // Unknown pairing hides the item. Deny-by-default matches the server, and a
  // missing rule is a generation bug rather than a permission.
  if (rule === undefined) return false;
  return rule.allow;
}
