"""Session store and revocation — TST-SEC-003 · STEP-002.08.

WHAT THESE ARE PROVING
    That a credential already in someone's hands stops working. Every other test
    in this file exists to stop that one from becoming vacuous — a store whose
    revocation only takes effect at expiry passes a naive "revoke then check the
    flag" test while changing nothing about what an attacker can do.

    So the central assertion is always: revoke, then present the token, **before
    its natural expiry**, and require refusal.
"""

from __future__ import annotations

import asyncio
import uuid
from collections.abc import Awaitable, Callable
from datetime import UTC, datetime, timedelta

import psycopg
import pytest
from dbcheck import DSN, requires_db
from provisioning import (
    create_organization,
    grant_membership,
    provision_user,
    revoke_membership,
)
from sessions import (
    REASON_ADMIN,
    REASON_SIGN_OUT,
    SessionError,
    hash_token,
    live_session_count,
    record_guest_session,
    record_session,
    revoke_all_for_user,
    revoke_guest_session,
    revoke_session,
    validate_guest_session,
    validate_session,
)


def run_as_owner[T](
    fn: Callable[[psycopg.AsyncCursor[tuple[object, ...]]], Awaitable[T]],
) -> T:
    async def scenario() -> T:
        async with await psycopg.AsyncConnection.connect(DSN) as conn:
            async with conn.cursor() as cur:
                result = await fn(cur)
            await conn.commit()
            return result

    return asyncio.run(scenario())


def unique(prefix: str) -> str:
    return f"{prefix}-{uuid.uuid4().hex[:12]}"


async def _org_and_user(
    cur: psycopg.AsyncCursor[tuple[object, ...]],
) -> tuple[uuid.UUID, uuid.UUID]:
    subject = unique("oidc|session")
    user = await provision_user(cur, idp_subject=subject, email=f"{subject}@example.test")
    org_id = uuid.uuid4()
    await cur.execute("SELECT set_config('app.current_org', %s, true)", (str(org_id),))
    await create_organization(
        cur,
        organization_id=org_id,
        slug=unique("org"),
        display_name="Session Fixture Org",
        owner_user_id=user.user_id,
    )
    return org_id, user.user_id


def _later(minutes: int = 60) -> datetime:
    return datetime.now(UTC) + timedelta(minutes=minutes)


# --- REQ-PRIV-001: the raw token is never stored -----------------------------


class TestTokensAreNeverStoredRaw:
    def test_the_hash_format_matches_the_typescript_implementation(self) -> None:
        """A CROSS-LANGUAGE CONTRACT, pinned with a vector from the other side.

        Guest tokens are minted in `apps/web/src/auth/guest.ts` and stored by this
        module. If the two hash differently every guest session fails to
        validate — and it fails as `unknown_token`, which is exactly what a forged
        token looks like, so the symptom would not point at the cause.

        This vector was generated by RUNNING the TypeScript `hashGuestToken`, not
        by running `hash_token`. A vector produced by the code under test proves
        only that the code agrees with itself.
        """
        assert (
            hash_token("journeylab-cross-language-vector")
            == "tebMu3MmsW06KO8YwQzwz3mvnVCydfwzvkYdlyRjJ5E"
        )

    def test_the_hash_is_unpadded(self) -> None:
        """`btoa(...).replace(/=+$/, '')` on the TypeScript side strips padding.

        Base64 of a 32-byte digest is 44 characters with one '=' of padding. Keep
        the padding and the strings differ while the bytes match — the worst kind
        of mismatch, because both sides look correct in isolation.
        """
        assert not hash_token("anything").endswith("=")
        assert len(hash_token("anything")) == 43

    def test_an_empty_token_is_refused_rather_than_hashed(self) -> None:
        """Hashing "" yields a perfectly good digest, and a row keyed on it would
        be a session anyone could claim by presenting nothing."""
        with pytest.raises(SessionError):
            hash_token("")

    @requires_db
    def test_no_raw_token_reaches_the_database(self) -> None:
        token = unique("raw-token-canary")

        async def check(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> list[str]:
            org_id, user_id = await _org_and_user(cur)
            await record_session(
                cur, organization_id=org_id, user_id=user_id, token=token, expires_at=_later()
            )
            await cur.execute(
                "SELECT token_hash FROM sessions WHERE organization_id = %s", (str(org_id),)
            )
            return [str(r[0]) for r in await cur.fetchall()]

        stored = run_as_owner(check)
        assert stored, "no session row written — precondition failed, not a pass"
        assert token not in stored
        assert hash_token(token) in stored


# --- REQ-SEC-003: revocation ends an ALREADY-ISSUED credential ---------------


class TestRevocationEndsALiveSession:
    @requires_db
    def test_a_revoked_session_fails_before_its_expiry(self) -> None:
        """The assertion the whole sub-step exists for.

        `expires_at` is an hour away throughout, so nothing here can pass by the
        session simply having timed out.
        """
        token = unique("tok")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[bool, bool, str]:
            org_id, user_id = await _org_and_user(cur)
            session_id = await record_session(
                cur, organization_id=org_id, user_id=user_id, token=token, expires_at=_later()
            )
            before = await validate_session(cur, token=token)
            await revoke_session(
                cur,
                organization_id=org_id,
                session_id=session_id,
                reason=REASON_SIGN_OUT,
                actor_id=user_id,
            )
            after = await validate_session(cur, token=token)
            return before.valid, after.valid, str(after.reason)

        was_valid, still_valid, reason = run_as_owner(scenario)
        assert was_valid, "the session was not valid to begin with — the test proves nothing"
        assert not still_valid
        assert reason == "revoked"

    @requires_db
    def test_revocation_stamps_rather_than_deletes(self) -> None:
        """Deleting erases the evidence an investigation needs."""
        token = unique("tok")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[int, str, str]:
            org_id, user_id = await _org_and_user(cur)
            session_id = await record_session(
                cur, organization_id=org_id, user_id=user_id, token=token, expires_at=_later()
            )
            await revoke_session(
                cur,
                organization_id=org_id,
                session_id=session_id,
                reason=REASON_ADMIN,
                actor_id=None,
            )
            await cur.execute(
                "SELECT count(*), max(revoked_at)::text, max(revoked_reason) "
                "FROM sessions WHERE id = %s",
                (str(session_id),),
            )
            row = await cur.fetchone()
            assert row is not None
            return int(str(row[0])), str(row[1]), str(row[2])

        count, revoked_at, reason = run_as_owner(scenario)
        assert count == 1, "the row was deleted"
        assert revoked_at != "None"
        assert reason == REASON_ADMIN

    @requires_db
    def test_revoking_one_session_leaves_the_others_alive(self) -> None:
        """Signing out on a phone must not sign the laptop out too."""
        phone, laptop = unique("tok-phone"), unique("tok-laptop")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[bool, bool]:
            org_id, user_id = await _org_and_user(cur)
            phone_id = await record_session(
                cur, organization_id=org_id, user_id=user_id, token=phone, expires_at=_later()
            )
            await record_session(
                cur, organization_id=org_id, user_id=user_id, token=laptop, expires_at=_later()
            )
            await revoke_session(
                cur,
                organization_id=org_id,
                session_id=phone_id,
                reason=REASON_SIGN_OUT,
                actor_id=user_id,
            )
            return (
                (await validate_session(cur, token=phone)).valid,
                (await validate_session(cur, token=laptop)).valid,
            )

        phone_valid, laptop_valid = run_as_owner(scenario)
        assert not phone_valid
        assert laptop_valid

    @requires_db
    def test_revoke_all_ends_every_session_for_that_user_only(self) -> None:
        mine_a, mine_b, theirs = unique("a"), unique("b"), unique("c")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[int, bool]:
            org_id, user_id = await _org_and_user(cur)
            other_subject = unique("oidc|other")
            other = await provision_user(
                cur, idp_subject=other_subject, email=f"{other_subject}@example.test"
            )
            await grant_membership(
                cur,
                organization_id=org_id,
                user_id=other.user_id,
                role_key="trip_viewer",
                actor_id=user_id,
            )
            for tok in (mine_a, mine_b):
                await record_session(
                    cur, organization_id=org_id, user_id=user_id, token=tok, expires_at=_later()
                )
            await record_session(
                cur,
                organization_id=org_id,
                user_id=other.user_id,
                token=theirs,
                expires_at=_later(),
            )

            await revoke_all_for_user(
                cur,
                organization_id=org_id,
                user_id=user_id,
                reason=REASON_ADMIN,
                actor_id=None,
            )
            return (
                await live_session_count(cur, organization_id=org_id, user_id=user_id),
                (await validate_session(cur, token=theirs)).valid,
            )

        mine_left, other_still_valid = run_as_owner(scenario)
        assert mine_left == 0
        assert other_still_valid, "revoke-all reached another user's session"


class TestRevocationCascadesFromMembership:
    """Closes STEP-002.04's second partial.

    `.04` recorded: "state is revoked and `active_role_keys` respects it, so the
    next authorization check fails. Ending an already-issued token needs the
    session store from `.05`." This is that ending.
    """

    @requires_db
    def test_revoking_a_membership_revokes_that_users_sessions(self) -> None:
        token = unique("tok")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[bool, str]:
            org_id, user_id = await _org_and_user(cur)
            await grant_membership(
                cur,
                organization_id=org_id,
                user_id=user_id,
                role_key="trip_viewer",
                actor_id=user_id,
            )
            await record_session(
                cur, organization_id=org_id, user_id=user_id, token=token, expires_at=_later()
            )
            await revoke_membership(
                cur,
                organization_id=org_id,
                user_id=user_id,
                role_key="trip_viewer",
                actor_id=user_id,
            )
            outcome = await validate_session(cur, token=token)
            return outcome.valid, str(outcome.reason)

        still_valid, reason = run_as_owner(scenario)
        assert not still_valid, (
            "revoking a membership left a live session holding the role it removed"
        )
        assert reason == "revoked"


# --- guest sessions -----------------------------------------------------------


class TestGuestSessions:
    @requires_db
    def test_a_revoked_guest_session_fails_before_expiry(self) -> None:
        """A guest session lasts seven days (ADR-014). Revoked on day one without
        this check, it would keep working for six more."""
        token = unique("guest")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> tuple[bool, bool]:
            await record_guest_session(cur, token=token, expires_at=_later(60 * 24 * 7))
            before = await validate_guest_session(cur, token=token)
            await revoke_guest_session(cur, token=token, reason=REASON_SIGN_OUT)
            after = await validate_guest_session(cur, token=token)
            return before.valid, after.valid

        was_valid, still_valid = run_as_owner(scenario)
        assert was_valid
        assert not still_valid

    @requires_db
    def test_an_unknown_guest_token_is_refused(self) -> None:
        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> str:
            return str((await validate_guest_session(cur, token=unique("never-issued"))).reason)

        assert run_as_owner(scenario) == "unknown_token"

    @requires_db
    def test_the_guest_table_has_no_tenant_column(self) -> None:
        """§6 of the sub-step: a guest has no tenant, so there is no column to
        leave null. Asserted against the schema so the decision cannot be quietly
        reversed by adding one."""

        async def columns(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> set[str]:
            await cur.execute(
                "SELECT column_name FROM information_schema.columns "
                "WHERE table_schema='public' AND table_name='guest_sessions'"
            )
            return {str(r[0]) for r in await cur.fetchall()}

        found = run_as_owner(columns)
        assert found, "guest_sessions not found — precondition failed"
        assert "organization_id" not in found


# --- the reason vocabulary ----------------------------------------------------


class TestRevocationReasons:
    @requires_db
    def test_an_unknown_reason_is_refused(self) -> None:
        """Free text cannot be aggregated. "How many sessions did an administrator
        end last week" is unanswerable over a column of prose."""

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> None:
            org_id, user_id = await _org_and_user(cur)
            session_id = await record_session(
                cur,
                organization_id=org_id,
                user_id=user_id,
                token=unique("tok"),
                expires_at=_later(),
            )
            await revoke_session(
                cur,
                organization_id=org_id,
                session_id=session_id,
                reason="because I felt like it",
                actor_id=None,
            )

        with pytest.raises(SessionError, match="unknown revocation reason"):
            run_as_owner(scenario)

    @requires_db
    def test_the_database_refuses_a_revocation_without_a_reason(self) -> None:
        """Enforced by CHECK, not by remembering. A revoked_at with no reason means
        one of the two writes was forgotten."""

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> None:
            org_id, user_id = await _org_and_user(cur)
            session_id = await record_session(
                cur,
                organization_id=org_id,
                user_id=user_id,
                token=unique("tok"),
                expires_at=_later(),
            )
            await cur.execute(
                "UPDATE sessions SET revoked_at = now() WHERE id = %s", (str(session_id),)
            )

        with pytest.raises(psycopg.errors.CheckViolation):
            run_as_owner(scenario)


# --- expiry still works -------------------------------------------------------


class TestExpiry:
    @requires_db
    def test_an_expired_session_is_refused(self) -> None:
        """Revocation must not have replaced expiry."""
        token = unique("tok")

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> str:
            org_id, user_id = await _org_and_user(cur)
            await record_session(
                cur, organization_id=org_id, user_id=user_id, token=token, expires_at=_later(1)
            )
            outcome = await validate_session(
                cur, token=token, now=datetime.now(UTC) + timedelta(hours=2)
            )
            return str(outcome.reason)

        assert run_as_owner(scenario) == "expired"

    @requires_db
    def test_recording_an_already_expired_session_is_refused(self) -> None:
        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> None:
            org_id, user_id = await _org_and_user(cur)
            await record_session(
                cur,
                organization_id=org_id,
                user_id=user_id,
                token=unique("tok"),
                expires_at=datetime.now(UTC) - timedelta(minutes=1),
            )

        with pytest.raises(SessionError, match="already expired"):
            run_as_owner(scenario)

    def test_a_naive_expiry_is_refused(self) -> None:
        """DTZ: a naive datetime compared against an aware one raises at runtime,
        and the place to find that out is not production."""

        async def scenario(cur: psycopg.AsyncCursor[tuple[object, ...]]) -> None:
            await record_session(
                cur,
                organization_id=uuid.uuid4(),
                user_id=uuid.uuid4(),
                token="t",  # noqa: S106 - a session token, not a password
                expires_at=datetime(2030, 1, 1),  # noqa: DTZ001 - the point of the test
            )

        class _Dead:
            async def execute(self, q: str, p: tuple[object, ...] = (), /) -> object:
                raise AssertionError("must refuse before touching the database")

            async def fetchone(self) -> tuple[object, ...] | None:
                return None

            async def fetchall(self) -> list[tuple[object, ...]]:
                return []

        with pytest.raises(SessionError, match="timezone-aware"):
            asyncio.run(scenario(_Dead()))  # type: ignore[arg-type]
